## DP-1 Oliver Adler demo

Nakoniec som sa rozhodol pre hľadanie implicitných vzťahov medzi vzormi. Používal som zatiaľ iba organizačné vzory.

In [415]:
import os
import pandas as pd
import numpy as np
from itertools import product
import transformers
import tensorflow as tf
from sklearn.metrics.pairwise import cosine_similarity,euclidean_distances
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from transformers import LongformerTokenizerFast, \
LongformerModel, LongformerTokenizer, LongformerConfig, Trainer, TrainingArguments, EvalPrediction, AutoTokenizer, AutoModel
from transformers.models.longformer.modeling_longformer import LongformerPreTrainedModel, LongformerClassificationHead

from tensorflow.keras import layers
from tensorflow.keras import losses

Pre toto demo som použil vzory z jazyka ProjectManagementPatternLanguage. Z každého vzoru vezmem jeho názov, počiatočný kontext (= problém ktorý rieši) a jeho konečný kontext. Text rozdeľujem podľa schémy, ktorú vzory z tejto kolekcie majú. 

In [352]:
directory = "patterns"
starting_contexts = []
resulting_contexts = []
pattern_names = []
for filename in os.listdir(directory):
    print(filename)
    with open(directory+"/"+filename) as f:
        lines = f.readlines()
        pattern_names.append(lines[0].replace('\n',''))
        starting_context = ""
        
        resulting_context = ""
        starting_context_flag = False
        resulting_context_flag = False
        for line in lines:
            #end of resulting context statement
            if "✥" in line and resulting_context_flag:
                break
            
            #beginning of starting context statement
            if "✥" in line and not starting_context_flag:
                starting_context_flag = True
                continue
                
            #beginning of resulting context statement
            if "Therefore:" in line and starting_context_flag:
                starting_context_flag = False
                resulting_context_flag = True
                continue

            if starting_context_flag and line != "\n":
                starting_context+=line

            if resulting_context_flag and line != "\n":
                resulting_context+=line
      
        starting_contexts.append(starting_context.translate({ord('\n'): None}))
        resulting_contexts.append(resulting_context.translate({ord('\n'): None}))

BuildPrototypes.txt
CommunityOfTrust.txt
CompletionHeadroom.txt
DayCare.txt
DeveloperControlsProcess.txt
DevelopmentEpisode.txt
DontInteruptAnInterrupt.txt
GetOnWithIt.txt
ImpliedRequirements.txt
IncrementalIntegration.txt
InformalLaborPlan.txt
InterruptsUnjamBlocking.txt
MercenaryAnalyst.txt
NamedStableBases.txt
PrivateWorld.txt
ProgrammingEpisode.txt
RecommitmentMeeting.txt
SacrificeOnePerson.txt
SizeTheSchedule.txt
SomeoneAlwaysMakesProgress.txt
SurrogateCustomer.txt
TakeNoSmallSlips.txt
TeamPerTask.txt
WorkFlowsInward.txt
WorkQueue.txt
WorkSplit.txt


In [353]:
patterns=[]
for i,pattern_name in enumerate(pattern_names):
    patterns.append(pattern_name)
    patterns.append(starting_contexts[i])
    patterns.append(resulting_contexts[i])

In [358]:
d = {"pattern_names": pattern_names, 'starting_contexts': starting_contexts, "resulting_contexts": resulting_contexts}
df = pd.DataFrame(data=d)

In [359]:
df

pattern_names  \
0                 Build Prototypes   
1               Community Of Trust   
2              Completion Headroom   
3                         Day Care   
4       Developer Controls Process   
5              Development Episode   
6     Don't Interrupt An Interrupt   
7                   Get On With It   
8             Implied Requirements   
9          Incremental Integration   
10             Informal Labor Plan   
11       Interrupts Unjam Blocking   
12               Mercenary Analyst   
13              Named Stable Bases   
14                   Private World   
15             Programming Episode   
16           Recommitment Meeting    
17           Sacrifice One Person    
18               Size The Schedule   
19  Someone Always Makes Progress    
20              Surrogate Customer   
21             Take No Small Slips   
22                   Team Per Task   
23               Work Flows Inward   
24                      Work Queue   
25                      Work Split   

                                    starting_contexts  \
0   A project must test requirements and design de...   
1   It is essential that the people in a team trus...   
2   Every project must commit to delivery on a few...   
3   Your experts are spending all their time mento...   
4   A development culture, like any culture, can b...   
5   It's important to build on the collective stre...   
6   It's important to balance a desire that Someon...   
7   You can't wait until you have every last requi...   
8   A commitment implies an agreement between peop...   
9   For iterative development to work well, it is ...   
10  A schedule of developer work tasks can both as...   
11  A comprehensive scheduling plan is difficult i...   
12  Technical documentation is the dirty work ever...   
13  It is important to integrate software frequent...   
14  How can we balance the need for developers to ...   
15  Programming is the act of deciding now what wi...   
16  If a Product Initiative is in jeopardy because...   
17  Small distractions can add up, and sap the str...   
18  Both overly ambitious schedules and overly gen...   
19  It is important to keep a team moving forward ...   
20  It is important to exchange ideas and clarify ...   
21  It's difficult to know how long a project shou...   
22  Large distractions (usually called crises) mus...   
23  An organization must seek a structure that bes...   
24  It is difficult to do linear, monochronic sche...   
25  A work group has an obligation to make its eff...   

                                   resulting_contexts  
0   Build an isolated prototype solution whose pur...  
1   Do things that explicitly demonstrate trust, s...  
2   Project work group completion dates from remai...  
3   Put one expert in charge of all the novices, l...  
4   Make the Developer the focal point of process ...  
5   Approach all development as a group activity a...  
6   If a developer is already working in "interrup...  
7   As soon as you have confidence about some proj...  
8   Select and name chunks of functionality. Use n...  
9   Provide a mechanism to allow developers to bui...  
10  Let individuals devise their own short-term pl...  
11  If a role is about to block on a critical reso...  
12  Hire a technical writer, proficient in the nec...  
13  Stabilize system interfaces — the architectu...  
14  Provide a mechanism where developers can maint...  
15  Develop a program in discrete episodes. Select...  
16  Assemble a meeting of interested management an...  
17  Assign just one person to it until it gets han...  
18  Reward developers for negotiating a schedule t...  
19  Whatever you try, ensure that someone on the t...  
20  Create a SurrogateCustomer role in the project...  
21  Prefer a single large slip to several small sl...  
22  One approach is to split the team. Sort the ac...  
23  Work should flow in to developer from stakehol...  
24  Produce a schedule that is simply a prioritize... 

Zo vzorov vytváram dvojice, kde pre dvojicu vzorov X a Y, budem mať v dataframe ich názvy, počiatočný kontext vzoru X a konečný kontext vzoru Y 

In [360]:
df_new = pd.DataFrame(list(product(df.pattern_names, df.pattern_names)), columns=['pattern_name1','pattern_name2'])
df_new

pattern_name1               pattern_name2
0    Build Prototypes            Build Prototypes
1    Build Prototypes          Community Of Trust
2    Build Prototypes         Completion Headroom
3    Build Prototypes                    Day Care
4    Build Prototypes  Developer Controls Process
..                ...                         ...
671        Work Split         Take No Small Slips
672        Work Split               Team Per Task
673        Work Split           Work Flows Inward
674        Work Split                  Work Queue
675        Work Split                  Work Split

[676 rows x 2 columns]

In [361]:
df_new["resulting_context"] = df_new.apply(lambda row: df[df["pattern_names"]==str(row.pattern_name1)].resulting_contexts.item(), axis=1)
df_new

pattern_name1               pattern_name2  \
0    Build Prototypes            Build Prototypes   
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
..                ...                         ...   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   
675        Work Split                  Work Split   

                                     resulting_context  
0    Build an isolated prototype solution whose pur...  
1    Build an isolated prototype solution whose pur...  
2    Build an isolated prototype solution whose pur...  
3    Build an isolated prototype solution whose pur...  
4    Build an isolated prototype solution whose pur...  
..                                                 ...  
671  Divide a task into an urgent and deferred comp...  
672  Divide a task into an urgent and deferred comp...  
673  Divide a task into an urgent and deferred comp...  
674  Divide a task into an urgent and deferred comp...  
675  Divide a task into an urgent and deferred comp...  

[676 rows x 3 columns]

In [362]:
df_new["starting_context"] = df_new.apply(lambda row: df[df["pattern_names"]==str(row.pattern_name2)].starting_contexts.item(), axis=1)
df_new

pattern_name1               pattern_name2  \
0    Build Prototypes            Build Prototypes   
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
..                ...                         ...   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   
675        Work Split                  Work Split   

                                     resulting_context  \
0    Build an isolated prototype solution whose pur...   
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
..                                                 ...   
671  Divide a task into an urgent and deferred comp...   
672  Divide a task into an urgent and deferred comp...   
673  Divide a task into an urgent and deferred comp...   
674  Divide a task into an urgent and deferred comp...   
675  Divide a task into an urgent and deferred comp...   

                                      starting_context  
0    A project must test requirements and design de...  
1    It is essential that the people in a team trus...  
2    Every project must commit to delivery on a few...  
3    Your experts are spending all their time mento...  
4    A development culture, like any culture, can b...  
..                                                 ...  
671  It's difficult to know how long a project shou...  
672  Large distractions (usually called crises) mus...  
673  An organization must seek a structure that bes...  
674  It is difficult to do linear, monochronic sche...  
675  A work group has an obligation to make its eff...  

[676 rows x 4 columns]

In [363]:
#Vymažem záznamy, kde X a Y sú rovnaké vzory
df_final = df_new[df_new.pattern_name1 != df_new.pattern_name2]
df_final

pattern_name1               pattern_name2  \
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
5    Build Prototypes         Development Episode   
..                ...                         ...   
670        Work Split          Surrogate Customer   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   

                                     resulting_context  \
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
5    Build an isolated prototype solution whose pur...   
..                                                 ...   
670  Divide a task into an urgent and deferred comp...   
671  Divide a task into an urgent and deferred comp...   
672  Divide a task into an urgent and deferred comp...   
673  Divide a task into an urgent and deferred comp...   
674  Divide a task into an urgent and deferred comp...   

                                      starting_context  
1    It is essential that the people in a team trus...  
2    Every project must commit to delivery on a few...  
3    Your experts are spending all their time mento...  
4    A development culture, like any culture, can b...  
5    It's important to build on the collective stre...  
..                                                 ...  
670  It is important to exchange ideas and clarify ...  
671  It's difficult to know how long a project shou...  
672  Large distractions (usually called crises) mus...  
673  An organization must seek a structure that bes...  
674  It is difficult to do linear, monochronic sche...  

[650 rows x 4 columns]

## Skladanie vzorov do sekvencií (nápad)

V tomto bode som skúsil zo sekvencie opísanej v jazyku vzorov ProjectManagementPatternLanguage 
(A Story About Project Management - https://sites.google.com/a/scrumplop.org/published-patterns/Organizational-Patterns-of-Agile-Software-Development/bookoutline/thepatternlanguages/organizationdesignpatterns/projectmanagementpatternlanguage?authuser=0). 


Z príbehu som vybral postupnosti vzorov tak ako išli za sebou. Napríklad prvý je spomínaný vzor BuildPrototypes a následne bol aplikovaný SizeTheSchedule. Takže do tabuľky spravím záznam sequence==1 pre záznam kde sa nachádza tento pár. Keďže som sa chcel zamerať na to kedy, respektíve po aplikovaní akého vzrou je môžné/vhodné aplikovať druhý vzor, bral som tento vzťah len pre dvojicu po sebe idúcich vzorov v príbehu. Teda, po SizeTheSchedule nasleduje vzor NamedStableBases. Dvojica SizeTheSchedule a NamedStableBases budú mať sequence==1, ale pár BuildPrototypes a NamedStableBases bude mať 0 (Nemusí to byť správne uvažovanie). 

In [364]:
df_final["sequence"]=0
df_final

C:\Users\olive\AppData\Local\Temp\ipykernel_4724\4076506384.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["sequence"]=0


pattern_name1               pattern_name2  \
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
5    Build Prototypes         Development Episode   
..                ...                         ...   
670        Work Split          Surrogate Customer   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   

                                     resulting_context  \
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
5    Build an isolated prototype solution whose pur...   
..                                                 ...   
670  Divide a task into an urgent and deferred comp...   
671  Divide a task into an urgent and deferred comp...   
672  Divide a task into an urgent and deferred comp...   
673  Divide a task into an urgent and deferred comp...   
674  Divide a task into an urgent and deferred comp...   

                                      starting_context  sequence  
1    It is essential that the people in a team trus...         0  
2    Every project must commit to delivery on a few...         0  
3    Your experts are spending all their time mento...         0  
4    A development culture, like any culture, can b...         0  
5    It's important to build on the collective stre...         0  
..                                                 ...       ...  
670  It is important to exchange ideas and clarify ...         0  
671  It's difficult to know how long a project shou...         0  
672  Large distractions (usually called crises) mus...         0  
673  An organization must seek a structure that bes...         0  
674  It is difficult to do linear, monochronic sche...         0  

[650 rows x 5 columns]

In [365]:
#vytvorené dvojice z príbehu
indexes = []

indexes.append(df_final.index[(df_final.pattern_name1=="Build Prototypes") & (df_final.pattern_name2=="Size The Schedule")])
indexes.append(df_final.index[(df_final.pattern_name1=="Size The Schedule") & (df_final.pattern_name2=="Named Stable Bases")])
indexes.append(df_final.index[(df_final.pattern_name1=="Named Stable Bases") & (df_final.pattern_name2=="Private World")])
indexes.append(df_final.index[(df_final.pattern_name1=="Private World") & (df_final.pattern_name2=="Developer Controls Process")])
indexes.append(df_final.index[(df_final.pattern_name1=="Developer Controls Process") & (df_final.pattern_name2=="Work Flows Inward")])
indexes.append(df_final.index[(df_final.pattern_name1=="Developer Controls Process") & (df_final.pattern_name2=="Work Queue")])
indexes.append(df_final.index[(df_final.pattern_name1=="Developer Controls Process") & (df_final.pattern_name2=="Informal Labor Plan")])
indexes.append(df_final.index[(df_final.pattern_name1=="Developer Controls Process") & (df_final.pattern_name2=="Programming Episode")])
indexes.append(df_final.index[(df_final.pattern_name1=="Work Queue") & (df_final.pattern_name2=="Take No Small Slips")])
indexes.append(df_final.index[(df_final.pattern_name1=="Informal Labor Plan") & (df_final.pattern_name2=="Take No Small Slips")])
indexes.append(df_final.index[(df_final.pattern_name1=="Programming Episode") & (df_final.pattern_name2=="Take No Small Slips")])
indexes.append(df_final.index[(df_final.pattern_name1=="Take No Small Slips") & (df_final.pattern_name2=="Recommitment Meeting ")])
indexes.append(df_final.index[(df_final.pattern_name1=="Take No Small Slips") & (df_final.pattern_name2=="Team Per Task")])
indexes.append(df_final.index[(df_final.pattern_name1=="Take No Small Slips") & (df_final.pattern_name2=="Sacrifice One Person ")])
indexes.append(df_final.index[(df_final.pattern_name1=="Team Per Task") & (df_final.pattern_name2=="Someone Always Makes Progress ")])

indexes

[Int64Index([18], dtype='int64'),
 Int64Index([481], dtype='int64'),
 Int64Index([352], dtype='int64'),
 Int64Index([368], dtype='int64'),
 Int64Index([127], dtype='int64'),
 Int64Index([128], dtype='int64'),
 Int64Index([114], dtype='int64'),
 Int64Index([119], dtype='int64'),
 Int64Index([645], dtype='int64'),
 Int64Index([281], dtype='int64'),
 Int64Index([411], dtype='int64'),
 Int64Index([562], dtype='int64'),
 Int64Index([568], dtype='int64'),
 Int64Index([563], dtype='int64'),
 Int64Index([591], dtype='int64')]

In [366]:
for index in indexes:
    df_final.loc[index,'sequence']=1
df_final[df_final['sequence']==1]

pattern_name1                   pattern_name2  \
18             Build Prototypes               Size The Schedule   
114  Developer Controls Process             Informal Labor Plan   
119  Developer Controls Process             Programming Episode   
127  Developer Controls Process               Work Flows Inward   
128  Developer Controls Process                      Work Queue   
281         Informal Labor Plan             Take No Small Slips   
352          Named Stable Bases                   Private World   
368               Private World      Developer Controls Process   
411         Programming Episode             Take No Small Slips   
481           Size The Schedule              Named Stable Bases   
562         Take No Small Slips           Recommitment Meeting    
563         Take No Small Slips           Sacrifice One Person    
568         Take No Small Slips                   Team Per Task   
591               Team Per Task  Someone Always Makes Progress    
645                  Work Queue             Take No Small Slips   

                                     resulting_context  \
18   Build an isolated prototype solution whose pur...   
114  Make the Developer the focal point of process ...   
119  Make the Developer the focal point of process ...   
127  Make the Developer the focal point of process ...   
128  Make the Developer the focal point of process ...   
281  Let individuals devise their own short-term pl...   
352  Stabilize system interfaces — the architectu...   
368  Provide a mechanism where developers can maint...   
411  Develop a program in discrete episodes. Select...   
481  Reward developers for negotiating a schedule t...   
562  Prefer a single large slip to several small sl...   
563  Prefer a single large slip to several small sl...   
568  Prefer a single large slip to several small sl...   
591  One approach is to split the team. Sort the ac...   
645  Produce a schedule that is simply a prioritize...   

                                      starting_context  sequence  
18   Both overly ambitious schedules and overly gen...         1  
114  A schedule of developer work tasks can both as...         1  
119  Programming is the act of deciding now what wi...         1  
127  An organization must seek a structure that bes...         1  
128  It is difficult to do linear, monochronic sche...         1  
281  It's difficult to know how long a project shou...         1  
352  How can we balance the need for developers to ...         1  
368  A development culture, like any culture, can b...         1  
411  It's difficult to know how long a project shou...         1  
481  It is important to integrate software frequent...         1  
562  If a Product Initiative is in jeopardy because...         1  
563  Small distractions can add up, and sap the str...         1  
568  Large distractions (usually called crises) mus...         1  
591  It is important to keep a team moving forward ...         1  
645  It's difficult to know how long a project shou...         1

## Použitie Neurónovej siete

Zo získaných dát som sa pokúsil spraviť demo neúronovej siete na klasifikáciu dvojíc textov. Teda podobnosť medzi konečným kontextom (resulting_context) vzoru X a začiatočným kontextom (starting_context) vzoru Y. Kde ak tieto kontexy sú podobné, je možné povedať že vzor Y môže byť použitý po vzore X. Zároveň by sieť pracovala s informáciou o tom či už boli v sekvencií čo som robil v prechádzajúcom úseku kódu.

Avšak model, ktorý by dokázal pozerať na sémantiku textov, v mojom prípade to bol BERT respektíve model na ňom založený, dokázal zobrať iba texty do veľkosti 509, čo je príliš málo na moje textové opisy. Existujú riešenia založené na modeli BERT, ktoré zvládnu aj dlhšie texty ako BigBird alebo LongFormer, tie sa mi však nepodarilo spojazdniť zatiaľ. 

In [176]:
max(df_final["starting_context"].apply(len))

1506

In [216]:
val_df["starting_context"].apply(len)

147     324
148    1506
149     232
151     861
152    1346
153     663
154    1003
155    1075
156     492
157     709
158    1281
159     644
160     476
161     324
162    1506
163     232
164     449
166    1346
167     663
168    1003
169    1075
170     492
171     709
172    1281
173     644
174     476
175     324
176    1506
177     232
178     449
179     861
181     663
182    1003
183    1075
184     492
185     709
186    1281
187     644
188     476
189     324
190    1506
191     232
192     449
193     861
194    1346
Name: starting_context, dtype: int64

## Iné riešenie (bez neurónovej siete)

Za použitia BERT modelu all-mpnet-base-v2, ktorý je natrénovaný a pripravený na použitie, viem vytvoriť vektorovú reprezentáciu textu, kde je zachovaná aj jeho sémantika. Vektory oboch kontextov viem porovnávať na základe metrík kosínusová podobnosť alebo euklidovksá vzdialenosť. Tieto mezriky podobností vektorov môžem použiť ako vstupy do ML modelu.

In [416]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2')


In [294]:
df_final

pattern_name1                   pattern_name2  \
1    Build Prototypes      Developer Controls Process   
2    Build Prototypes             Informal Labor Plan   
3    Build Prototypes              Named Stable Bases   
4    Build Prototypes                   Private World   
5    Build Prototypes             Programming Episode   
..                ...                             ...   
190        Work Queue               Size The Schedule   
191        Work Queue  Someone Always Makes Progress    
192        Work Queue             Take No Small Slips   
193        Work Queue                   Team Per Task   
194        Work Queue               Work Flows Inward   

                                     resulting_context  \
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
5    Build an isolated prototype solution whose pur...   
..                                                 ...   
190  Produce a schedule that is simply a prioritize...   
191  Produce a schedule that is simply a prioritize...   
192  Produce a schedule that is simply a prioritize...   
193  Produce a schedule that is simply a prioritize...   
194  Produce a schedule that is simply a prioritize...   

                                      starting_context  sequence  
1    A development culture, like any culture, can b...         0  
2    A schedule of developer work tasks can both as...         0  
3    It is important to integrate software frequent...         0  
4    How can we balance the need for developers to ...         0  
5    Programming is the act of deciding now what wi...         0  
..                                                 ...       ...  
190  Both overly ambitious schedules and overly gen...         0  
191  It is important to keep a team moving forward ...         0  
192  It's difficult to know how long a project shou...         1  
193  Large distractions (usually called crises) mus...         0  
194  An organization must seek a structure that bes...         0  

[182 rows x 5 columns]

In [302]:
#vytváranie vektorových reprezentácií oboch kontextov
df_final['starting_embedding'] = df_final['starting_context'].apply(model.encode)
df_final['resulting_embedding'] = df_final['resulting_context'].apply(model.encode)

C:\Users\olive\AppData\Local\Temp\ipykernel_4724\3252037246.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['starting_embedding'] = df_final['starting_context'].apply(model.encode)
C:\Users\olive\AppData\Local\Temp\ipykernel_4724\3252037246.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['resulting_embedding'] = df_final['resulting_context'].apply(model.encode)


In [374]:
df_final

pattern_name1               pattern_name2  \
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
5    Build Prototypes         Development Episode   
..                ...                         ...   
670        Work Split          Surrogate Customer   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   

                                     resulting_context  \
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
5    Build an isolated prototype solution whose pur...   
..                                                 ...   
670  Divide a task into an urgent and deferred comp...   
671  Divide a task into an urgent and deferred comp...   
672  Divide a task into an urgent and deferred comp...   
673  Divide a task into an urgent and deferred comp...   
674  Divide a task into an urgent and deferred comp...   

                                      starting_context  sequence  \
1    It is essential that the people in a team trus...         0   
2    Every project must commit to delivery on a few...         0   
3    Your experts are spending all their time mento...         0   
4    A development culture, like any culture, can b...         0   
5    It's important to build on the collective stre...         0   
..                                                 ...       ...   
670  It is important to exchange ideas and clarify ...         0   
671  It's difficult to know how long a project shou...         0   
672  Large distractions (usually called crises) mus...         0   
673  An organization must seek a structure that bes...         0   
674  It is difficult to do linear, monochronic sche...         0   

                                   starting_embeddings  \
1    [0.033992566, 0.0021839319, -0.0064396067, 0.0...   
2    [-0.06432862, 0.046334974, -0.015850563, -0.08...   
3    [0.069971845, 0.056567065, -0.00016744515, -0....   
4    [0.04957857, 0.05668401, -0.046187162, -0.0080...   
5    [0.0035809937, 0.0012670304, -0.019009784, 0.0...   
..                                                 ...   
670  [0.07129714, 0.05089531, -0.022737782, 0.02519...   
671  [0.015812408, 0.10102768, -0.009773148, -0.043...   
672  [0.0011973408, 0.04903567, 0.011451123, -0.010...   
673  [0.04887739, 0.0011259597, -0.029870065, -0.04...   
674  [0.023785634, 0.08178888, -0.02493737, -0.0035...   

                                  resulting_embeddings  
1    [0.026106788, 0.04424294, 0.006456062, 0.00941...  
2    [0.026106788, 0.04424294, 0.006456062, 0.00941...  
3    [0.026106788, 0.04424294, 0.006456062, 0.00941...  
4    [0.026106788, 0.04424294, 0.006456062, 0.00941...  
5    [0.026106788, 0.04424294, 0.006456062, 0.00941...  
..                                                 ...  
670  [0.0035704507, 0.05868317, -0.023359573, -0.02...  
671  [0.0035704507, 0.05868317, -0.023359573, -0.02...  
672  [0.0035704507, 0.05868317, -0.023359573, -0.02...  
673  [0.0035704507, 0.05868317, -0.023359573, -0.02...  
674  [0.0035704507, 0.05868317, -0.023359573, -0.02...  

[650 rows x 7 columns]

In [376]:
#počítanie kosínusovej podobnosti

cos_sim = []
for pairs in df_final[['resulting_embeddings','starting_embeddings']].values:
    cos_sim.append(cosine_similarity([pairs[0],pairs[1]]))
cos_values = []
for values in cos_sim:
    cos_values.append(values[0][1])

[array([[0.9999999 , 0.25257915],
        [0.25257915, 0.99999994]], dtype=float32),
 array([[0.9999999 , 0.14763771],
        [0.14763771, 1.        ]], dtype=float32),
 array([[0.9999999 , 0.22450677],
        [0.22450677, 1.0000002 ]], dtype=float32),
 array([[0.9999999 , 0.27709526],
        [0.27709526, 1.0000001 ]], dtype=float32),
 array([[0.9999999 , 0.06495934],
        [0.06495934, 1.0000001 ]], dtype=float32),
 array([[0.9999999 , 0.12164262],
        [0.12164262, 1.0000004 ]], dtype=float32),
 array([[0.9999999 , 0.25244573],
        [0.25244573, 1.0000002 ]], dtype=float32),
 array([[0.9999999 , 0.23166391],
        [0.23166391, 0.9999998 ]], dtype=float32),
 array([[0.9999999 , 0.29673555],
        [0.29673555, 0.99999976]], dtype=float32),
 array([[0.9999999, 0.1845297],
        [0.1845297, 1.0000002]], dtype=float32),
 array([[0.9999999 , 0.14992702],
        [0.14992702, 1.        ]], dtype=float32),
 array([[0.9999999 , 0.24772869],
        [0.24772869, 1.0000002 ]], 

In [404]:
#počítanie euklidovskej vzdialenosti


euc_dist = []
for pairs in df_final[['resulting_embeddings','starting_embeddings']].values:
    euc_dist.append(euclidean_distances([pairs[0],pairs[1]]))
euc_dist

euc_values = []
for values in euc_dist:
    euc_values.append(values[0][1])

[array([[0.       , 1.2226373],
        [1.2226373, 0.       ]], dtype=float32),
 array([[0.       , 1.3056511],
        [1.3056511, 0.       ]], dtype=float32),
 array([[0.       , 1.2453861],
        [1.2453861, 0.       ]], dtype=float32),
 array([[0.       , 1.2024182],
        [1.2024182, 0.       ]], dtype=float32),
 array([[0.       , 1.3675092],
        [1.3675092, 0.       ]], dtype=float32),
 array([[0.       , 1.3254112],
        [1.3254112, 0.       ]], dtype=float32),
 array([[0.       , 1.2227463],
        [1.2227463, 0.       ]], dtype=float32),
 array([[0.       , 1.2396258],
        [1.2396258, 0.       ]], dtype=float32),
 array([[0.       , 1.1859716],
        [1.1859716, 0.       ]], dtype=float32),
 array([[0.       , 1.2770828],
        [1.2770828, 0.       ]], dtype=float32),
 array([[0.       , 1.3038965],
        [1.3038965, 0.       ]], dtype=float32),
 array([[0.      , 1.226598],
        [1.226598, 0.      ]], dtype=float32),
 array([[0.      , 1.257617],
  

In [378]:
df_final['cos_similarity']=cos_values

C:\Users\olive\AppData\Local\Temp\ipykernel_4724\3776327664.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['cos_similarity']=cos_values


In [409]:
df_final['euc_distance']=euc_values

C:\Users\olive\AppData\Local\Temp\ipykernel_4724\2520422237.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['euc_distance']=euc_values


Výsledná tabuľka s metrikami

In [410]:
df_final

pattern_name1               pattern_name2  \
1    Build Prototypes          Community Of Trust   
2    Build Prototypes         Completion Headroom   
3    Build Prototypes                    Day Care   
4    Build Prototypes  Developer Controls Process   
5    Build Prototypes         Development Episode   
..                ...                         ...   
670        Work Split          Surrogate Customer   
671        Work Split         Take No Small Slips   
672        Work Split               Team Per Task   
673        Work Split           Work Flows Inward   
674        Work Split                  Work Queue   

                                     resulting_context  \
1    Build an isolated prototype solution whose pur...   
2    Build an isolated prototype solution whose pur...   
3    Build an isolated prototype solution whose pur...   
4    Build an isolated prototype solution whose pur...   
5    Build an isolated prototype solution whose pur...   
..                                                 ...   
670  Divide a task into an urgent and deferred comp...   
671  Divide a task into an urgent and deferred comp...   
672  Divide a task into an urgent and deferred comp...   
673  Divide a task into an urgent and deferred comp...   
674  Divide a task into an urgent and deferred comp...   

                                      starting_context  sequence  \
1    It is essential that the people in a team trus...         0   
2    Every project must commit to delivery on a few...         0   
3    Your experts are spending all their time mento...         0   
4    A development culture, like any culture, can b...         0   
5    It's important to build on the collective stre...         0   
..                                                 ...       ...   
670  It is important to exchange ideas and clarify ...         0   
671  It's difficult to know how long a project shou...         0   
672  Large distractions (usually called crises) mus...         0   
673  An organization must seek a structure that bes...         0   
674  It is difficult to do linear, monochronic sche...         0   

                                   starting_embeddings  \
1    [0.033992566, 0.0021839319, -0.0064396067, 0.0...   
2    [-0.06432862, 0.046334974, -0.015850563, -0.08...   
3    [0.069971845, 0.056567065, -0.00016744515, -0....   
4    [0.04957857, 0.05668401, -0.046187162, -0.0080...   
5    [0.0035809937, 0.0012670304, -0.019009784, 0.0...   
..                                                 ...   
670  [0.07129714, 0.05089531, -0.022737782, 0.02519...   
671  [0.015812408, 0.10102768, -0.009773148, -0.043...   
672  [0.0011973408, 0.04903567, 0.011451123, -0.010...   
673  [0.04887739, 0.0011259597, -0.029870065, -0.04...   
674  [0.023785634, 0.08178888, -0.02493737, -0.0035...   

                                  resulting_embeddings  cos_similarity  \
1    [0.026106788, 0.04424294, 0.006456062, 0.00941...        0.252579   
2    [0.026106788, 0.04424294, 0.006456062, 0.00941...        0.147638   
3    [0.026106788, 0.04424294, 0.006456062, 0.00941...        0.224507   
4    [0.026106788, 0.04424294, 0.006456062, 0.00941...        0.277095   
5    [0.026106788, 0.04424294, 0.006456062, 0.00941...        0.064959   
..                                                 ...             ...   
670  [0.0035704507, 0.05868317, -0.023359573, -0.02...        0.220626   
671  [0.0035704507, 0.05868317, -0.023359573, -0.02...        0.437349   
672  [0.0035704507, 0.05868317, -0.023359573, -0.02...        0.475158   
673  [0.0035704507, 0.05868317, -0.023359573, -0.02...        0.314848   
674  [0.0035704507, 0.05868317, -0.023359573, -0.02...        0.430706   

     euc_distance  
1        1.222637  
2        1.305651  
3        1.245386  
4        1.202418  
5        1.367509  
..            ...  
670      1.248498  
671      1.060803  
672      1.024541  
673      1.170599  
674      1.067046  

[650 rows x 9 columns]

Najväčšiu podobnosť mali vzory CompletionHeadRoom a WorkSplit čo keď sa pozrieme do ích textových opisov tak je vidieť, že tam naozaj existuje nejaký vzťah

In [418]:
df_final.sort_values(by=['cos_similarity'],ascending=False).head(20)

pattern_name1                   pattern_name2  \
77              Completion Headroom                      Work Split   
602               Work Flows Inward      Developer Controls Process   
352              Named Stable Bases                   Private World   
30               Community Of Trust      Developer Controls Process   
427           Recommitment Meeting        Interrupts Unjam Blocking   
178    Don't Interrupt An Interrupt                   Team Per Task   
479               Size The Schedule       Interrupts Unjam Blocking   
244         Incremental Integration             Informal Labor Plan   
271             Informal Labor Plan       Interrupts Unjam Blocking   
489               Size The Schedule             Take No Small Slips   
267             Informal Labor Plan                  Get On With It   
500  Someone Always Makes Progress     Don't Interrupt An Interrupt   
497  Someone Always Makes Progress                         Day Care   
501  Someone Always Makes Progress                   Get On With It   
630                      Work Queue    Don't Interrupt An Interrupt   
660                      Work Split             Informal Labor Plan   
519  Someone Always Makes Progress                       Work Split   
669                      Work Split  Someone Always Makes Progress    
264             Informal Labor Plan      Developer Controls Process   
635                      Work Queue       Interrupts Unjam Blocking   

                                     resulting_context  \
77   Project work group completion dates from remai...   
602  Work should flow in to developer from stakehol...   
352  Stabilize system interfaces — the architectu...   
30   Do things that explicitly demonstrate trust, s...   
427  Assemble a meeting of interested management an...   
178  If a developer is already working in "interrup...   
479  Reward developers for negotiating a schedule t...   
244  Provide a mechanism to allow developers to bui...   
271  Let individuals devise their own short-term pl...   
489  Reward developers for negotiating a schedule t...   
267  Let individuals devise their own short-term pl...   
500  Whatever you try, ensure that someone on the t...   
497  Whatever you try, ensure that someone on the t...   
501  Whatever you try, ensure that someone on the t...   
630  Produce a schedule that is simply a prioritize...   
660  Divide a task into an urgent and deferred comp...   
519  Whatever you try, ensure that someone on the t...   
669  Divide a task into an urgent and deferred comp...   
264  Let individuals devise their own short-term pl...   
635  Produce a schedule that is simply a prioritize...   

                                      starting_context  sequence  \
77   A work group has an obligation to make its eff...         0   
602  A development culture, like any culture, can b...         0   
352  How can we balance the need for developers to ...         1   
30   A development culture, like any culture, can b...         0   
427  A comprehensive scheduling plan is difficult i...         0   
178  Large distractions (usually called crises) mus...         0   
479  A comprehensive scheduling plan is difficult i...         0   
244  A schedule of developer work tasks can both as...         0   
271  A comprehensive scheduling plan is difficult i...         0   
489  It's difficult to know how long a project shou...         0   
267  You can't wait until you have every last requi...         0   
500  It's important to balance a desire that Someon...         0   
497  Your experts are spending all their time mento...         0   
501  You can't wait until you have every last requi...         0   
630  It's important to balance a desire that Someon...         0   
660  A schedule of developer work tasks can both as...         0   
519  A work group has an obligation to make its eff...         0   
669  It is important to keep a team moving forward ...         0   
264  A development 

Naopak najmenej podobné kontexty mali MercenaryAnalyst a NamedStableBases.

In [419]:
df_final.sort_values(by=['cos_similarity']).head(20)

pattern_name1            pattern_name2  \
325          Mercenary Analyst       Named Stable Bases   
298  Interrupts Unjam Blocking        Mercenary Analyst   
442      Sacrifice One Person          Build Prototypes   
566        Take No Small Slips       Surrogate Customer   
454      Sacrifice One Person         Mercenary Analyst   
211       Implied Requirements                 Day Care   
225       Implied Requirements    Sacrifice One Person    
549        Take No Small Slips                 Day Care   
637                 Work Queue       Named Stable Bases   
17            Build Prototypes    Sacrifice One Person    
329          Mercenary Analyst    Sacrifice One Person    
288  Interrupts Unjam Blocking      Completion Headroom   
5             Build Prototypes      Development Episode   
547        Take No Small Slips       Community Of Trust   
355         Named Stable Bases    Sacrifice One Person    
301  Interrupts Unjam Blocking      Programming Episode   
555        Take No Small Slips  Incremental Integration   
333          Mercenary Analyst      Take No Small Slips   
80                    Day Care      Completion Headroom   
537         Surrogate Customer    Sacrifice One Person    

                                     resulting_context  \
325  Hire a technical writer, proficient in the nec...   
298  If a role is about to block on a critical reso...   
442  Assign just one person to it until it gets han...   
566  Prefer a single large slip to several small sl...   
454  Assign just one person to it until it gets han...   
211  Select and name chunks of functionality. Use n...   
225  Select and name chunks of functionality. Use n...   
549  Prefer a single large slip to several small sl...   
637  Produce a schedule that is simply a prioritize...   
17   Build an isolated prototype solution whose pur...   
329  Hire a technical writer, proficient in the nec...   
288  If a role is about to block on a critical reso...   
5    Build an isolated prototype solution whose pur...   
547  Prefer a single large slip to several small sl...   
355  Stabilize system interfaces — the architectu...   
301  If a role is about to block on a critical reso...   
555  Prefer a single large slip to several small sl...   
333  Hire a technical writer, proficient in the nec...   
80   Put one expert in charge of all the novices, l...   
537  Create a SurrogateCustomer role in the project...   

                                      starting_context  sequence  \
325  It is important to integrate software frequent...         0   
298  Technical documentation is the dirty work ever...         0   
442  A project must test requirements and design de...         0   
566  It is important to exchange ideas and clarify ...         0   
454  Technical documentation is the dirty work ever...         0   
211  Your experts are spending all their time mento...         0   
225  Small distractions can add up, and sap the str...         0   
549  Your experts are spending all their time mento...         0   
637  It is important to integrate software frequent...         0   
17   Small distractions can add up, and sap the str...         0   
329  Small distractions can add up, and sap the str...         0   
288  Every project must commit to delivery on a few...         0   
5    It's important to build on the collective stre...         0   
547  It is essential that the people in a team trus...         0   
355  Small distractions can add up, and sap the str...         0   
301  Programming is the act of deciding now what wi...         0   
555  For iterative development to work well, it is ...         0   
333  It's difficult to know how long a project shou...         0   
80   Every project must commit to delivery on a few...         0   
537  Small distractions can add up, and sap the str...         0   

                                   starting_embeddings  \
325  [-0.008631551, 0.04980158, -0.008348653, -0.05...   
298  [0.02013

Jeden zo spôsobov ako použiť získané data s ML je napríklad použitie regresie, v tomto prípade som skúsil logistickú regresiu kde ako vstup idú metriky podbnosti. Samozrejme model potrebuje aj label-y takže som skúsil použiť moje predtým vytvorené informácie, či sú vzoru v postupnosti alebo nie. Ale nakoľko som použil len jednu sekvenciu (aj to možno nie s úplne správnym uvažovaním) model nedokázal na testovacej vzroke správne určiť 3 dvojice vzorov, ktoré som identifikoval ako páry v postupnosti

In [411]:
X = df_final[['cos_similarity','euc_distance']]
y = df_final['sequence']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=16)


In [412]:
logreg = LogisticRegression(random_state=16)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

In [414]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[160,   0],
       [  3,   0]], dtype=int64)

## Čo ďalej

V prvom rade rožšíriť databázu, spravovať aj ostatné jazkyky vzorov, prípadne ich príbehy o postupnosti (sekvencii). Taktiež nájsť riešnie ako použiť modely neurónovej siete na klasifikáciu párov textov (kontextov) na základe ich podobnosti.

Pri prípade používania alternatívneho riešenia (text ako vektor). Navrhnutie metódy, ktorá bude schopná klasifikovať vzťahy vzorov na zákade ich vektorovej podobnosti